# Generated by Django 5.2.9 on 2025-12-24 10:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='МВС СТ', max_length=200, verbose_name='Название сайта')),
                ('organization_name', models.CharField(blank=True, default='МВС СТ', max_length=200, verbose_name='Название организации')),
                ('tagline', models.CharField(blank=True, default='', max_length=250, verbose_name='Слоган')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип (PNG/SVG как картинка)')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Адрес')),
                ('about_title', models.CharField(blank=True, default='О нас', max_length=200, verbose_name="Заголовок 'О нас'")),
                ('about_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name="Текст 'О нас'")),
                ('mission_title', models.CharField(blank=True, default='Миссия', max_length=200, verbose_name="Заголовок 'Миссия'")),
                ('mission_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name="Текст 'Миссия'")),
                ('vk', models.URLField(blank=True, default='', verbose_name='VK')),
                ('telegram', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, default='', verbose_name='YouTube')),
                ('seo_title', models.CharField(blank=True, default='', max_length=255, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, default='', max_length=300, verbose_name='SEO description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
