# Generated by Django 5.2.9 on 2025-12-25 12:00

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="about_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="vk",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="youtube",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contacts_intro",
            field=models.TextField(blank=True, default="", verbose_name="Контакты: вводный текст"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contacts_map_embed",
            field=models.TextField(blank=True, default="", verbose_name="Контакты: код карты (iframe)"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contacts_title",
            field=models.CharField(blank=True, default="Контакты", max_length=200, verbose_name="Контакты: заголовок"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/", verbose_name="Главная: фоновое изображение"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.TextField(blank=True, default="", verbose_name="Главная: подзаголовок"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Главная: заголовок"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_about_text",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default="", verbose_name="Главная: текст об организации"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_about_title",
            field=models.CharField(blank=True, default="Об организации", max_length=200, verbose_name="Главная: блок об организации"),
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("organization-about", "Об организации"),
                            ("organization-key-facts", "Ключевые факты"),
                            ("organization-leadership", "Руководство"),
                            ("organization-performance", "Оценка деятельности"),
                            ("career", "Карьера"),
                        ],
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("lead", models.TextField(blank=True, default="", verbose_name="Лид")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(blank=True, default="", verbose_name="Контент")),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
        migrations.CreateModel(
            name="KeyFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Подпись")),
                ("value", models.CharField(max_length=120, verbose_name="Значение")),
                ("description", models.CharField(blank=True, default="", max_length=200, verbose_name="Описание")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Ключевой факт",
                "verbose_name_plural": "Ключевые факты",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="ФИО")),
                ("position", models.CharField(max_length=200, verbose_name="Должность")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="leadership/", verbose_name="Фото")),
                ("bio", django_ckeditor_5.fields.CKEditor5Field(blank=True, default="", verbose_name="Биография")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Руководитель",
                "verbose_name_plural": "Руководство",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                ("image", models.ImageField(blank=True, null=True, upload_to="performance/", verbose_name="Изображение")),
                ("description", models.TextField(blank=True, default="", verbose_name="Описание")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Оценка деятельности",
                "verbose_name_plural": "Оценка деятельности",
                "ordering": ["order", "-date"],
            },
        ),
    ]
