# Generated by Django 5.2.9 on 2025-12-25 18:05

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_content_and_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="organization_name",
            field=models.CharField(
                blank=True,
                default="АНО «МосводостокСтройТрест»",
                max_length=200,
                verbose_name="Название организации",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(
                default="АНО «МосводостокСтройТрест»",
                max_length=200,
                verbose_name="Название сайта",
            ),
        ),
        migrations.RemoveField(
            model_name="leadershipmember",
            name="bio",
        ),
        migrations.CreateModel(
            name="ContentSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("body", django_ckeditor_5.fields.CKEditor5Field(blank=True, default="", verbose_name="Контент")),
                ("image", models.ImageField(blank=True, null=True, upload_to="sections/", verbose_name="Изображение")),
                ("button_text", models.CharField(blank=True, default="", max_length=120, verbose_name="Текст кнопки")),
                ("button_url", models.URLField(blank=True, default="", verbose_name="Ссылка кнопки")),
                (
                    "style",
                    models.CharField(
                        choices=[("default", "По умолчанию"), ("accent", "Акцентный фон")],
                        default="default",
                        max_length=20,
                        verbose_name="Стиль",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="sections",
                        to="core.contentpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция страницы",
                "verbose_name_plural": "Секции страницы",
                "ordering": ["order", "id"],
            },
        ),
    ]
