# Generated by Django 5.2.9 on 2025-12-24 10:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обложка')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
