# Generated by Django 5.2.9 on 2025-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="blog/videos/", verbose_name="Видео (файл)"),
        ),
    ]
